steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag1 .
  automapSubstitutions: true
images:
- 'us-west2-docker.pkg.dev/peak-ascent-434105-d7/quickstart-docker-repo/quickstart-image:tag1'

options:
  logging: 'CLOUD_LOGGING_ONLY'
